### ISSUE TITLE
Implement network configuration

### ISSUE THREAD

**Issue by Guerlielton** [dokku/ansible-dokku#102]
Do you think It may be possible to network from a module?
On dokku_network.
for example 

```version: '2'
services:
  web:
     build: . 
      links: 
         - "db:database"
  db:
      image: postgres
```
I sometimes coded with python actually, but maybe I could have a look if this feature may interest you and I found sometime later.

**Comment by josegonzalez** [comment]
@ltalirz Just a note, we support specifying an associated app network, but not necessarily specifying `--link` except through docker options.

**Comment by ltalirz** [comment]
hi @Guerlielton - that certainly sounds doable.
As @josegonzalez mentions you would need to call docker directly but that is not a problem.

Writing an ansible module is really quite straightforward, I suggest you have a look at the [`dokku_proxy`](https://github.com/dokku/ansible-dokku/blob/master/library/dokku_proxy.py) for example, and see the [contributing guide](https://github.com/dokku/ansible-dokku/blob/master/CONTRIBUTING.md) for local setup.
Feel free to get started!

On a more general note, this issue touches on one feature that is currently missing in dokku, namely support for `docker-compose`.
@josegonzalez were just discussing potential formats for writing down a configuration of an app - what are your thoughts on the `docker-compose.yaml`?

**Comment by josegonzalez** [comment]
I think we have support for `dokku_docker_options` which may work for arbitrary flags (though in this case, a dedicated library that interacts with the `network` plugin is best).

I don't think docker-compose support made a ton of sense in the past - [PR here](https://github.com/dokku/dokku/pull/1596) - but maybe make more sense now? The biggest issues I see are:

- lack of zero downtime support
- we'd have to figure out a way to properly inject the Docker images instead of having docker-compose rebuild
- how do we - and do we? - stop compose from starting certain containers?

Probably worth a separate discussion, but this is a bit more possible with custom builders and schedulers. Let me know if you want to talk about this on slack :)

**Comment by ltalirz** [comment]
@Guerlielton Does https://github.com/dokku/ansible-dokku/pull/108 address your use case?

**Comment by Guerlielton** [comment]
I think yes, I will test in my case thanks for feedback  @ltalirz  and  @lemoony  congrats for good job. 
I will close this issue
